services:
  gome:
    build:
      context: ./golang
    container_name: gome
    volumes:
      - ./code/:/go/src
      - ./code/gome:/go/src/gome
      - ./supervisor:/etc/supervisor/conf.d
    ports:
      - "8088:8088"
    tty: true

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - ./rabbitmq/etc/:/etc/rabbitmq/
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: "username"
      RABBITMQ_DEFAULT_PASS: "password"
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:6.0
    container_name: redis
    ports:
      - "6379:6379"
